@startuml
skinparam backgroundColor #fafaff
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam rectangle {
  BackgroundColor #eaf4fb
  BorderColor #333366
}
skinparam diamond {
  BackgroundColor #f9e6e6
  BorderColor #aa2222
}
skinparam oval {
  BackgroundColor #e5ffe5
  BorderColor #228822
}
skinparam actor {
  BackgroundColor #ffffcc
  BorderColor #666600
}
skinparam arrow {
  Color #333366
}

start

:Run CLI Application;

diamond "Choose Game?" as ChooseGame
:If 'Tres' ->;
:Deal Cards to Players;
:Players Take Turns Playing Cards;
diamond "Player has 3 cards?" as Tres3Cards
Tres3Cards -down-> :Initiate 'Punishment Mechanic';
:Player selects number (1-100);
:Game generates secret number (1-100);
diamond "Player Number vs Secret Number" as PunishCompare
PunishCompare -left-> "Player's number HIGHER" :Punish Self;\nDraw random 1-5 cards;
PunishCompare -right-> "Player's number LOWER" :Punish All Others;\nDraw random 1-5 cards;
PunishCompare -down-> "EXACT MATCH" :Double Punishment;\nDraw random 2-10 cards;

:Continue Play;

diamond "Player plays all cards?" as TresWin
TresWin -down-> :Tres Game Ends;

ChooseGame -right-> :If 'Wordy' ->;
:Game selects random word;
:Player makes guess;
diamond "Guess length correct?" as WordyLength
WordyLength -left-> "No" :Show error;\nAsk for new guess;
WordyLength -right-> "Yes" :Provide feedback:\nCorrect letters & positions;
diamond "Guessed word correctly?" as WordyWin
WordyWin -left-> "No" :Repeat guess;
WordyWin -right-> :Wordy Game Ends;

:Show Results or Restart Option;
stop
@enduml